module.exports = {
    apps: [
      {
        name: '<APP_NAME>',
        exec_mode: 'cluster',
        instances: '2',
        script: 'node_modules/next/dist/bin/next',
        args: 'start -p 4000',
        node_args: ["--harmony"],
        ignore_watch: ["node_modules", "public", "logs", "logger", ".env", ".git", ".cache", ".npm", ".pm2", ".bun", ".yarn", ".next" ],
        max_memory_restart: "1G",
        restart_delay: 5000,
        exp_backoff_restart_delay: 100,
        max_restarts: 32,
        min_uptime: 10000,
        wait_ready: true,
        autorestart: true,
        env_local: {
          APP_ENV: 'local',
        },
        env_dev: {
          APP_ENV: 'dev',
        },
        env_production: {
          APP_ENV: 'production',
        },
        error_file: `./logs/root.err.log`,
        out_file: `./logs/root.out.log`,
      },
      {
        script: "./.sivium/healthCheck.js",
        watch: "./.sivium",
        name: "cluster-health",
        node_args: ["--harmony"],
        max_memory_restart: "1G",
        restart_delay: 5000,
        exp_backoff_restart_delay: 100,
        max_restarts: 32,
        min_uptime: 10000,
        wait_ready: true,
        autorestart: true,
        env: {
          CLUSTER_PORT: 4001,
          NODE_ENV: "DEV",
          TZ: 'Europe/Kyiv',
        },
        env_production: {
          CLUSTER_PORT: 4001,
          NODE_ENV: "production",
          TZ: 'Europe/Kyiv',
        },
        error_file: `./logs/health.err.log`,
        out_file: `./logs/health.out.log`,
      },
    ],
  }